<a href="https://colab.research.google.com/github/omkar-2483/Machine-Learning-Deep-Learning/blob/main/D3-Deep-Learning-with-PyTorch/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor

Import Tensor and check for CUDA Availability

In [2]:
import torch
torch.cuda.is_available()

True

# Creating Tensor and Operation

In [3]:
first_tensor = torch.tensor([[1,2,3,4],[5,6,7,8]])
second_tensor = torch.tensor([[2,3,5,4],[6,4,6,3]])

# addition
print(first_tensor+second_tensor)

tensor([[ 3,  5,  8,  8],
        [11, 10, 13, 11]])


In [4]:
# substraction
print(first_tensor-second_tensor)

tensor([[-1, -1, -2,  0],
        [-1,  2,  1,  5]])


To allocate Tensor to GPU

In [7]:
if torch.cuda.is_available(): device = 'cuda'
else: device='cpu'

print(device)

cuda


In [8]:
ten_a = torch.tensor([[1,2,3,4],[5,6,7,8]], device = device)
ten_b = torch.tensor([[2,3,5,4],[6,4,6,3]], device = device)
multi_ten = ten_a * ten_b
print(multi_ten)

tensor([[ 2,  6, 15, 16],
        [30, 24, 42, 24]], device='cuda:0')


Note that output is also allocated to GPU. cuda:0 inicate that tensor is allocated to first GPU

# Moving Tensor between CPUs and GPUs


Tensors are moved between CPUs and GPUs to leverage the GPU's faster processing capabilities, especially for large-scale neural network training.

* **CPU to GPU:** When training large neural networks or handling high-dimensional data (like images) that require faster computation, we move tensors to the GPU. This is because GPUs are optimized for parallel processing and can significantly speed up training.

* **GPU to CPU:** After training, if the output tensors need pre-processing and the libraries used (like NumPy) only support CPU data, we move the tensors back to the CPU. This ensures compatibility with these libraries for further data manipulation.

# Different Ways to Create Tensor

**Creating Tensors from Python Objects:**
You can create tensors from lists, tuples, or NumPy arrays using the torch.tensor method.



In [12]:
# initialize tensor from a list
ten_1 = torch.tensor([1,2,3,4,5])

# initialize tensor from tuple
ten_2 = torch.tensor((3,23,213,44,4))

# initialize tensor from nd array
import numpy as np
ten_3 = torch.tensor(np.array([23,43,44,45,55]))

print("tensor from list: ", ten_1)
print("tensor from tuple: ", ten_2)
print("tensor from nd array: ", ten_3)

tensor from list:  tensor([1, 2, 3, 4, 5])
tensor from tuple:  tensor([  3,  23, 213,  44,   4])
tensor from nd array:  tensor([23, 43, 44, 45, 55])


**Predefined Functions:** PyTorch provides functions like torch.empty(), torch.ones(), and torch.zeros() to create tensors with specific initial values.

In [14]:
empty_ten = torch.empty(2,5)
print("empty tensor: ", empty_ten)

ones_ten = torch.ones(3,5)
print("empty tensor: ", ones_ten)

zeros_ten = torch.zeros(3,5)
print("empty tensor: ", zeros_ten)

empty tensor:  tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31, 1.9447e+31, 2.1715e-18],
        [2.3081e-12, 1.8590e+34, 7.7767e+31, 1.7181e+19, 1.8990e+28]])
empty tensor:  tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
empty tensor:  tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [63]:
torch.full((4,5),5)

tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])

**Random Tensors**: Functions like torch.rand(), torch.randn(), and torch.randint() generate tensors with random values from different distributions.

In [61]:
# tensor filled with random numbers from a uniform distribution on interval [0-1]
tensor_rand_un = torch.rand(2,3)
print('tensor_rand_un: ',tensor_rand_un)

# tensor filled with random numbers from a normal distribution with 0 mean and 1 variance
tensor_rand_nor = torch.randn(2,3)
print('tensor_rand_nor: ',tensor_rand_nor)
print("mean of tensor_rand_nor", tensor_rand_nor.mean())

# tensor filled with random integers generated uniformly between specified interval
tensor_randint = torch.randint(1,10,(2,3))
print('tensor_randint: ',tensor_randint)

tensor_rand_un:  tensor([[0.8876, 0.9466, 0.3037],
        [0.0089, 0.3416, 0.2241]])
tensor_rand_nor:  tensor([[-0.3056,  0.2029,  0.6883],
        [ 0.8710,  0.5413,  0.5557]])
mean of tensor_rand_nor tensor(0.4256)
tensor_randint:  tensor([[8, 5, 4],
        [2, 2, 8]])


That's expected! The mean of a randomly generated tensor from a normal distribution N(0,1) is not exactly 0—it approaches 0 as the number of samples increases.

In [57]:
# To get same result everytime
torch.manual_seed(11)  # any integer
tensor_rand_un = torch.rand(2,3)
print('tensor_rand_un: ',tensor_rand_un)

tensor_rand_un:  tensor([[0.1490, 0.4866, 0.9857],
        [0.1684, 0.5839, 0.6936]])


**Similar Properties:** Use functions like torch.ones_like() to create tensors with properties (dtype, device, layout) similar to another tensor.

In [19]:
tensor_ones = torch.ones_like(tensor_randint)
print(tensor_ones)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [21]:
tensor_zeros = torch.zeros_like(tensor_randint)
print(tensor_zeros)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [62]:
tensor_seven = torch.full_like(tensor_randint, 7)
tensor_seven

tensor([[7, 7, 7],
        [7, 7, 7]])

# Tensor Attributes

In [26]:
tensor_1 = torch.tensor([1,2,3,4,5,6,7])
tensor_2 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], device=device)

**Device Location**: Use the device function to find out where the tensor is stored (CPU or GPU).

In [29]:
tensor_1.device

device(type='cpu')

In [30]:
tensor_2.device

device(type='cuda', index=0)

**Data Type:** The dtype function reveals the data type of the tensor elements (e.g., int64).

In [31]:
tensor_1.dtype

torch.int64

In [32]:
tensor_2.dtype

torch.int64

**Dimensions and Rank:** The shape function provides the dimensions of the tensor, and ndim gives the number of dimensions (rank).

In [33]:
tensor_1.shape

torch.Size([7])

In [34]:
tensor_2.shape

torch.Size([3, 3])

In [35]:
tensor_1.ndim

1

In [36]:
tensor_2.ndim

2

# Tensor Data Types

**Data Type Specification:** You can specify the data type of a tensor using the dtype argument, such as torch.int8 for 8-bit integers or torch.float32 for 32-bit floating points.

In [37]:
int_ten = torch.tensor([1,2,3,4,5], dtype=torch.int8)
int_ten.dtype

torch.int8

In [38]:
float_ten = torch.tensor([1,2,3,4,5], dtype=torch.float16)
float_ten.dtype

torch.float16

In [39]:
short_ten = torch.tensor([1,2,3,4,5], dtype=torch.int16)
short_ten.dtype

torch.int16

**Casting Tensors**: Tensors can be cast to different data types using functions like float() or the to() method.

In [40]:
int_ten = int_ten.float()
int_ten.dtype

torch.float32

In [41]:
very_short_ten = short_ten.to(dtype=torch.int8)
very_short_ten.dtype

torch.int8

In [42]:
short_ten.dtype

torch.int16

**Automatic Casting**: PyTorch automatically casts tensors to a larger data type during operations to ensure precision and manage memory consumption effectively.

In [43]:
(int_ten+short_ten).dtype

torch.float32

In [44]:
int_ten.dtype

torch.float32

In [45]:
short_ten.dtype

torch.int16

# Tensor Operation

**Indexing and Slicing**: Similar to NumPy, you can access single elements (indexing) and ranges of elements (slicing) in tensors.

In [65]:
ten_2 = torch.tensor([[1,2,3,4],[5,6,7,8,]])
ten_2[1,1]

tensor(6)

In [66]:
ten_2[1][1]

tensor(6)

In [75]:
ten_2[1,1].item()

6

In [67]:
ten_2[:,2]

tensor([3, 7])

In [78]:
ten_2[:]

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [79]:
ten_2[:][2]

IndexError: index 2 is out of bounds for dimension 0 with size 2

In [77]:
# ten_2[:,2].item() # error: Tensor with 2 elements cannot be converted to Scalar

In [70]:
ten_2[0,:]

tensor([1, 2, 3, 4])

In [71]:
ten_2[0][:]

tensor([1, 2, 3, 4])

In [83]:
ten_2[0:1, 1:3]

tensor([[2, 3]])

**Conditional Indexing**: You can extract data that meets specific criteria, such as values less than a certain number.

In [85]:
ten_2[ten_2<10]

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
ten_2[ten_2<5]

tensor([1, 2, 3, 4])

**Combining and Splitting**: Use torch.stack to combine tensors along a new dimension and torch.unbind to split tensors along a specified dimension.

In [89]:
ten_3 = torch.stack((ten_2, ten_2))
ten_3

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]])

In [90]:
ten_3.ndim

3

In [91]:
ten_3.shape

torch.Size([2, 2, 4])

In [92]:
ten_11, ten_12 = torch.unbind(ten_2)

In [93]:
ten_11

tensor([1, 2, 3, 4])

In [94]:
ten_12

tensor([5, 6, 7, 8])

In [95]:
# split columnwise
ten11, ten12, ten13, ten14 = torch.unbind(ten_2, dim=1)

In [96]:
ten11

tensor([1, 5])

In [97]:
ten13

tensor([3, 7])

# Mathematical Functions