# Classification Models
Continuous dependent vriable = use regression models
Categorical dependent variable = use classification models
 3 classification models
  * Logistic regression
  * Linear Discriminant Analysis (LDA)
  * K- nearest neighbour (KNN)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv('house_sold.csv', header=0)

In [4]:
df.head(5)

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347     0    4.0875            1   
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

# Logistic regression

Simple Logistic Regression

Way 1- using sklearn library

In [5]:
x = df[['price']]

In [6]:
y = df['Sold']

In [7]:
x.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [8]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
clf_lrs = LogisticRegression()

In [11]:
clf_lrs.fit(x,y)

LogisticRegression()

In [12]:
#find coefficient and intercept
clf_lrs.coef_

array([[-0.03571865]])

In [13]:
clf_lrs.intercept_

array([0.61477516])

In [14]:
# now you can use these B1 and B0 in logistic regression equation to predict values of y

Way 2- using stats model 

In [15]:
import statsmodels.api as sn

In [16]:
x_const = sn.add_constant(x)

In [17]:
x_const.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [18]:
import statsmodels.discrete.discrete_model as sm

In [19]:
logit = sm.Logit(y, x_const).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [20]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Tue, 20 Aug 2024   Pseudo R-squ.:                 0.01788
Time:                        15:47:43   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

Logistic Regression with multiple predictors

In [21]:
x = df.loc[:, df.columns != 'Sold']

In [22]:
y = df['Sold']

In [23]:
x.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347    4.0875            1   
1       7.332     12.17280        42  0.046146    4.9675            0   
2       7.394     46.19856        38  0.045764    4.9675            0   
3       9.268     11.26720        45  0.047151    6.0650            1   
4       8.824     11.28960        55  0.039474    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [24]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [25]:
clf_lr = LogisticRegression()
clf_lr.fit(x,y)

C:\Users\Shubham\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [26]:
clf_lr.coef_

array([[-0.24634681, -0.01729788, -0.11019278,  0.8625383 , -0.00599824,
         0.22821539, -0.21020419,  0.18007874, -0.09088653, -0.00705152,
        -0.00499201, -0.32611862, -0.10520943, -0.09486198, -0.01512214,
         0.20178583]])

In [27]:
clf_lr.intercept_

array([0.01670983])

Using Statsmodels

In [28]:
x_const = sn.add_constant(x)

In [29]:
x_const.head()

const  price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0    1.0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1    1.0   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2    1.0   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3    1.0   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4    1.0   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347    4.0875            1   
1       7.332     12.17280        42  0.046146    4.9675            0   
2       7.394     46.19856        38  0.045764    4.9675            0   
3       9.268     11.26720        45  0.047151    6.0650            1   
4       8.824     11.28960        55  0.039474    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [30]:
logit = sm.Logit(y, x_const).fit()

Optimization terminated successfully.
         Current function value: 0.556433
         Iterations 6


In [31]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      489
Method:                           MLE   Df Model:                           16
Date:                Tue, 20 Aug 2024   Pseudo R-squ.:                  0.1924
Time:                        15:47:44   Log-Likelihood:                -281.56
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 9.930e-21
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.1383      2.649     -0.807      0.420      -7.331       3.054
price                       -0.2741      0.033     -8.313      0.000      -0.339      -0.209
resid_area                   0.0192      0.027      0.720      0.471      -0.033       0.071
air_qual                    -7.4183      2.691     -2.757      0.006     -12.693      -2.144
room_num                     1.1067      0.277      4.001      0.000       0.565       1.649
age                         -0.0020      0.007     -0.302      0.762      -0.015       0.011
teachers                     0.3150      0.064      4.937      0.000       0.190       0.440
poor_prop                   -0.2077      0.034     -6.149      0.000      -0.274      -0.141
n_hos_beds                   0.1760      0.071      2.467      0.014       0.036       0.316
n_hot_rooms                 -0.0742      0.052     -1.439      0.150      -0.175       0.027
rainfall                    -0.0033      0.008     -0.394      0.693      -0.020       0.013
parks                       29.1089     24.177      1.204      0.229     -18.277      76.495
avg_dist                    -0.4017      0.098     -4.118      0.000      -0.593      -0.211
airport_YES                 -0.1524      0.211     -0.723      0.469      -0.565       0.261
waterbody_Lake              -0.1032      0.304     -0.340      0.734      -0.698       0.492
waterbody_Lake and River    -0.0626      0.328     -0.191      0.849      -0.705       0.580
waterbody_River              0.2394      0.256      0.937      0.349      -0.262       0.740
============================================================================================
"""

confusion matrix
-

In [32]:
# find probability of not sold and gets sold
clf_lr.predict_proba(x)

array([[0.12706304, 0.87293696],
       [0.39755536, 0.60244464],
       [0.98073172, 0.01926828],
       ...,
       [0.2859661 , 0.7140339 ],
       [0.28065305, 0.71934695],
       [0.16347665, 0.83652335]])

In [33]:
y_pred = clf_lr.predict(x)

In [34]:
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [35]:
# for boundry condition 0.3
y_pred_03 = (clf_lr.predict_proba(x)[:,1] >= 0.3)

In [36]:
y_pred_03

array([ True,  True, False,  True, False, False,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False,

In [37]:
# comparing accuracy of model

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
confusion_matrix?

Signature:
confusion_matrix(
    y_true,
    y_pred,
    *,
    labels=None,
    sample_weight=None,
    normalize=None,
)
Docstring:
Compute confusion matrix to evaluate the accuracy of a classification.

By definition a confusion matrix :math:`C` is such that :math:`C_{i, j}`
is equal to the number of observations known to be in group :math:`i` and
predicted to be in group :math:`j`.

Thus in binary classification, the count of true negatives is
:math:`C_{0,0}`, false negatives is :math:`C_{1,0}`, true positives is
:math:`C_{1,1}` and false positives is :math:`C_{0,1}`.

Read more in the :ref:`User Guide <confusion_matrix>`.

Parameters
----------
y_true : array-like of shape (n_samples,)
    Ground truth (correct) target values.

y_pred : array-like of shape (n_samples,)
    Estimated targets as returned by a classifier.

labels : array-like of shape (n_classes), default=None
    List of labels to index the matrix. This may be used to reorder
    or select a subset of labels.
    If

In [40]:
confusion_matrix(y, y_pred)

array([[196,  80],
       [ 81, 149]], dtype=int64)

In [41]:
# not sold, predicted not sold = 196 (specificity)
# not sold , predicted sold= 80 (false positive, type I error, 1-Specificity )
# sold, predicted not sold=81 (false negative, type II error)
# sold, predicted sold = 149 (1-type II error, power, )

In [42]:
confusion_matrix(y, y_pred_03)

array([[121, 155],
       [ 18, 212]], dtype=int64)

In [43]:
# see how false positive incresed

Model performance
-
precision = True Positive / (True Positive + false Positive)

recall/ power =  True Positive / (True Positive + False negative )


In [44]:
from sklearn.metrics import precision_score, recall_score

In [45]:
precision_score(y, y_pred)

0.6506550218340611

In [46]:
recall_score(y, y_pred)

0.6478260869565218

In [47]:
from sklearn.metrics import roc_auc_score

In [48]:
roc_auc_score(y, y_pred)

0.6789855072463769

# LDA- Linear Discriminant Analysis

In [50]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [51]:
clf_lda = LinearDiscriminantAnalysis()

In [52]:
clf_lda.fit(x,y)

LinearDiscriminantAnalysis()

In [53]:
y_pred_lda = clf_lda.predict(x)

In [54]:
y_pred_lda

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [58]:
confusion_matrix(y, y_pred_lda)

array([[192,  84],
       [ 79, 151]], dtype=int64)

In [60]:
# confusion_matrix(y_pred_lda, y)

# Train Test Split

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size = 0.2, random_state=0)

In [66]:
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(404, 16) (102, 16) (404,) (102,)


In [67]:
clf_LR = LogisticRegression()

In [68]:
clf_LR.fit(X_train, Y_train)

C:\Users\Shubham\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [69]:
y_test_pred = clf_LR.predict(X_test)

In [70]:
from sklearn.metrics import accuracy_score , confusion_matrix

In [71]:
confusion_matrix(Y_test, y_test_pred)

array([[37, 21],
       [14, 30]], dtype=int64)

In [72]:
accuracy_score(Y_test, y_test_pred)

0.6568627450980392

In [73]:
clf_LDA = LinearDiscriminantAnalysis()

In [74]:
clf_LDA.fit(X_train, Y_train)

LinearDiscriminantAnalysis()

In [78]:
y_test_pred_LDA = clf_LDA.predict(X_test)

In [79]:
confusion_matrix(Y_test, y_test_pred_LDA)

array([[34, 24],
       [11, 33]], dtype=int64)

In [80]:
accuracy_score(Y_test, y_test_pred_LDA)

0.6568627450980392

# KNN (K Nearest Neighbour)
Non Parametric Function

standardize the data  first- convert the mean=0 and standard deviation=1

In [82]:
from sklearn import preprocessing

In [84]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [85]:
X_train_s = scaler.transform(X_train)

In [87]:
scaler = preprocessing.StandardScaler().fit(X_test)

In [88]:
X_test_s =scaler.transform(X_test)

In [95]:
# X_train

In [96]:
X_train_s, X_test_s

(array([[ 0.44572353, -0.70492455, -0.42487874, ..., -0.48525664,
         -0.40529635,  1.3293319 ],
        [-0.09643431, -0.04487755, -1.24185891, ..., -0.48525664,
          2.4673304 , -0.75225758],
        [ 0.478253  , -0.88675963, -1.11148974, ..., -0.48525664,
         -0.40529635, -0.75225758],
        ...,
        [-0.36751323, -0.15941933, -0.0772276 , ..., -0.48525664,
          2.4673304 , -0.75225758],
        [-0.64943531, -0.60326872, -0.93766417, ..., -0.48525664,
         -0.40529635,  1.3293319 ],
        [ 0.05536988, -1.01275558, -0.3988049 , ..., -0.48525664,
         -0.40529635,  1.3293319 ]]),
 array([[ 3.46427198e-02, -1.26009787e+00, -7.59976330e-01, ...,
         -4.93864798e-01, -3.98862018e-01, -7.54473836e-01],
        [ 3.08888478e+00,  1.09537107e+00,  6.84309089e-01, ...,
         -4.93864798e-01, -3.98862018e-01, -7.54473836e-01],
        [ 7.92301952e-02,  4.28041039e-01,  1.73890573e-04, ...,
         -4.93864798e-01, -3.98862018e-01, -7.54473836e-

In [99]:
from sklearn.neighbors import KNeighborsClassifier

In [100]:
clf_knn_1 = KNeighborsClassifier(n_neighbors=1)

In [101]:
clf_knn_1.fit(X_train_s, Y_train)

KNeighborsClassifier(n_neighbors=1)

In [102]:
confusion_matrix(Y_test, clf_knn_1.predict(X_test_s))

array([[30, 28],
       [19, 25]], dtype=int64)

In [103]:
accuracy_score(Y_test, clf_knn_1.predict(X_test_s))

0.5392156862745098

In [104]:
clf_knn_3 = KNeighborsClassifier(n_neighbors=3)

In [105]:
clf_knn_3.fit(X_train_s, Y_train)

KNeighborsClassifier(n_neighbors=3)

In [106]:
accuracy_score(Y_test, clf_knn_3.predict(X_test_s))

0.5392156862745098

Single model for multiple values of K 
-

In [107]:
from sklearn.model_selection import GridSearchCV

In [108]:
params = {'n_neighbors':[1,2,3,4,5,6,7,8,9,10]}

In [110]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(), params)

In [111]:
grid_search_cv.fit(X_train_s, Y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [112]:
grid_search_cv.best_params_

{'n_neighbors': 9}

In [113]:
optimized_KNN = grid_search_cv.best_estimator_

In [114]:
y_test_pred = optimized_KNN.predict(X_test_s)

In [115]:
confusion_matrix(Y_test, y_test_pred)

array([[36, 22],
       [18, 26]], dtype=int64)

In [116]:
accuracy_score(Y_test, y_test_pred)

0.6078431372549019