# SVM based regressor

# Import libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("./Movie_regression.csv")

In [3]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

# missing  value imputation

In [5]:
# missing values in Time_taken
df['Time_taken'].mean()

157.3914979757085

In [6]:
df["Time_taken"].fillna(value= df["Time_taken"].mean(), inplace=True)

C:\Users\Shubham\AppData\Local\Temp\ipykernel_36192\1758753138.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Time_taken"].fillna(value= df["Time_taken"].mean(), inplace=True)


In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

# dummy variable creation

In [8]:
# 3D_available and Genre is categorical variable
df = pd.get_dummies(df, columns=["3D_available", "Genre"], drop_first=True)

In [9]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000              True         False   
1              42            462       43200             False         False   
2              38            458       69400             False          True   
3              45            472       66800              True         False   
4              55            395       72400             False         False   

   Genre_Drama  Genre_Thriller  
0        False            True  
1         True           False  
2        False           False  
3         True           False  
4         True           False

In [10]:
df["3D_available_YES"]= df["3D_available_YES"].astype(int)

In [11]:
df["Genre_Comedy"]= df["Genre_Comedy"].astype(int)
df["Genre_Drama"]= df["Genre_Drama"].astype(int)
df["Genre_Thriller"]= df["Genre_Thriller"].astype(int)

In [12]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000                 1             0   
1              42            462       43200                 0             0   
2              38            458       69400                 0             1   
3              45            472       66800                 1             0   
4              55            395       72400                 0             0   

   Genre_Drama  Genre_Thriller  
0            0               1  
1            1               0  
2            0               0  
3            1               0  
4            1               0

# X-Y split

In [15]:
X = df.loc[:, df.columns!="Collection"]

In [17]:
X.shape

(506, 19)

In [18]:
y= df["Collection"]

In [19]:
y.shape

(506,)

In [20]:
type(X)

pandas.core.frame.DataFrame

In [21]:
type(y)

pandas.core.series.Series

# Train Test Split

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [27]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 19), (102, 19), (404,), (102,))

# Standardizing data
converting mean and variance equal to 0 and  1 resp
two ways to standardize data= using StandarScaler and MinMaxScaler

In [24]:
from sklearn.preprocessing import StandardScaler

In [28]:
sc = StandardScaler().fit(X_train)

In [29]:
X_train_std = sc.transform(X_train)

In [30]:
X_train_std

array([[-0.37257438, -0.70492455,  0.42487874, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39709866, -0.04487755,  1.24185891, ..., -0.66547513,
        -0.48525664, -0.75225758],
       [-0.402693  , -0.88675963,  1.11148974, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.39805586, -0.15941933,  0.0772276 , ..., -0.66547513,
        -0.48525664, -0.75225758],
       [-0.38842357, -0.60326872,  0.93766417, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39951258, -1.01275558,  0.3988049 , ..., -0.66547513,
        -0.48525664,  1.3293319 ]])

In [31]:
X_test_std = sc.transform(X_test)

In [32]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

# Training regression tree
https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html

In [33]:
from sklearn.svm import SVR

In [34]:
# svr = SVR(kernel="linear", C=1000)

In [45]:
#check for c=500
svr= SVR(kernel="linear", C=500)

In [46]:
svr.fit(X_train_std, y_train)

SVR(C=500, kernel='linear')

# Predict values using trained model

In [47]:
y_train_pred = svr.predict(X_train_std)

In [48]:
y_test_pred = svr.predict(X_test_std)

In [49]:
y_test_pred

array([54172.88652594, 42360.53493594, 47535.6161038 , 18213.44501931,
       48306.49797341, 39911.30264079, 34154.82438396, 43328.81857968,
       30564.16305183, 47083.06891753, 12883.41530221, 38441.56120077,
       37564.58419372,  8833.24108759, 66743.92804381, 61806.13858547,
       38834.69156187, 65442.06460586, 57070.43984968, 43390.83509428,
       53825.48454162, 39211.12088433, 41594.24518385, 58253.12540463,
       43061.94784582, 13500.91595214, 41078.73255014, 29760.22077231,
       74387.42055942, 44639.66629805, 36802.04559594, 37452.7520558 ,
       37731.81412737, 41015.55708641, 52033.72818305, 35527.23097608,
       25303.12301261, 36494.03996199, 36688.32304647, 35826.51769434,
       47334.38882548, 45971.16054321, 44806.68292955, 27789.57095574,
       50531.91304271, 46829.47085744, 33272.97210625, 40080.92308753,
       15821.17728949, 51706.04815075, 41321.11684481, 39172.79222897,
       47629.5707835 , 67355.55689102, 25492.33272751, 41679.44337221,
      

 # Model performance

In [50]:
from sklearn.metrics import mean_squared_error , r2_score

In [51]:
mean_squared_error(y_test, y_test_pred)

160031907.61713442

In [52]:
r2_score(y_train, y_train_pred)

0.7125944752203937

In [53]:
r2_score(y_test, y_test_pred)

0.5028901447877382

# SVM based Clasification model

In [59]:
df = pd.read_csv("./Movie_classification.csv", header=0)

In [60]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

# missing values

In [62]:
df.Time_taken.fillna(value= df.Time_taken.mean(), inplace= True)

C:\Users\Shubham\AppData\Local\Temp\ipykernel_36192\4145810268.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Time_taken.fillna(value= df.Time_taken.mean(), inplace= True)


In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

# dummy variables 

In [64]:
df = pd.get_dummies(df, columns=["3D_available", "Genre"], drop_first=True, dtype=int)

In [65]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                 1             0            0               1  
1                 0             0            1               0  
2                 0             1            0               0  
3                 1             0            1               0  
4                 0             0            1               0  

[5 rows x 21 columns]

# X - y split

In [66]:
X = df.loc[:, df.columns!="Start_Tech_Oscar"]

In [67]:
X.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000                 1             0   
1              42            462       43200                 0             0   
2              38            458       69400                 0             1   
3              45            472       66800                 1             0   
4              55            395       72400                 0             0   

   Genre_Drama  Genre_Thriller  
0            0               1  
1            1               0  
2            0               0  
3            1               0  
4            1               0

In [68]:
y = df["Start_Tech_Oscar"]

In [69]:
y

0      1
1      0
2      1
3      1
4      1
      ..
501    0
502    0
503    0
504    0
505    0
Name: Start_Tech_Oscar, Length: 506, dtype: int64

In [70]:
type(X)

pandas.core.frame.DataFrame

In [71]:
type(y)

pandas.core.series.Series

# Train Test Split

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [74]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 20), (102, 20), (404,), (102,))

# Standardize data

In [82]:
from sklearn.preprocessing import StandardScaler

In [83]:
sc = StandardScaler().fit(X_train)

In [84]:
X_train_std = sc.transform(X_train)

In [85]:
X_test_std =  sc.transform(X_test)

In [86]:
X_train_std

array([[-0.37257438, -0.70492455,  0.42487874, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39709866, -0.04487755,  1.24185891, ..., -0.66547513,
        -0.48525664, -0.75225758],
       [-0.402693  , -0.88675963,  1.11148974, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.39805586, -0.15941933,  0.0772276 , ..., -0.66547513,
        -0.48525664, -0.75225758],
       [-0.38842357, -0.60326872,  0.93766417, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39951258, -1.01275558,  0.3988049 , ..., -0.66547513,
        -0.48525664,  1.3293319 ]])

In [87]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

In [93]:
# X_test_std.mean()

In [96]:
# X_test_std[0].mean()

# SVM based classifier

In [97]:
from sklearn import svm

In [101]:
svm_clf = svm.SVC(kernel="linear", C=0.01)

In [102]:
svm_clf.fit(X_train_std, y_train)

SVC(C=0.01, kernel='linear')

# predict values

In [103]:
y_train_pred = svm_clf.predict(X_train_std)

In [104]:
y_test_pred = svm_clf.predict(X_test_std)

In [106]:
y_test_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

# Model performance

In [107]:
 from sklearn.metrics import accuracy_score, confusion_matrix

In [108]:
confusion_matrix(y_test, y_test_pred)

array([[11, 33],
       [ 5, 53]], dtype=int64)

In [109]:
accuracy_score(y_test, y_test_pred)

0.6274509803921569

In [110]:
 # Number of support vectors for each class.
svm_clf.n_support_

array([186, 189])

# Grid Search 

In [136]:
from sklearn.model_selection import GridSearchCV

In [137]:
params = {'C':(0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000)}

In [138]:
svm_clf_1= svm.SVC(kernel = "linear")

In [139]:
svm_grid_lin = GridSearchCV(svm_clf_1, params, n_jobs=-1, cv=10, verbose=1, scoring="accuracy")

In [140]:
svm_grid_lin.fit(X_train_std, y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


GridSearchCV(cv=10, estimator=SVC(kernel='linear'), n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             scoring='accuracy', verbose=1)

In [141]:
svm_grid_lin.best_params_

{'C': 0.1}

In [142]:
linsvm_clf = svm_grid_lin.best_estimator_

In [143]:
confusion_matrix(y_test, linsvm_clf.predict(X_test_std))

array([[25, 19],
       [22, 36]], dtype=int64)

In [144]:
accuracy_score(y_test, linsvm_clf.predict(X_test_std))

0.5980392156862745

# polynomial svm classifier

In [124]:
svm_clf_p = svm.SVC(kernel= "poly", degree=2, C=0.1)

In [125]:
svm_clf_p.fit(X_train_std, y_train)

SVC(C=0.1, degree=2, kernel='poly')

In [126]:
y_train_pred = svm_clf_p.predict(X_train_std)
y_test_pred = svm_clf_p.predict(X_test_std)

In [127]:
accuracy_score(y_train, y_train_pred)

0.5544554455445545

In [128]:
accuracy_score(y_test, y_test_pred)

0.5588235294117647

In [130]:
svm_clf_p.n_support_

array([185, 194])

# SVM classifier with radial kernel

In [131]:
svm_clf_r = svm.SVC(kernel="rbf", gamma=0.5, C=10)

In [132]:
svm_clf_r.fit(X_train_std, y_train)

SVC(C=10, gamma=0.5)

In [133]:
y_test_pred = svm_clf_r.predict(X_test_std)

In [134]:
accuracy_score(y_test, y_test_pred)

0.6176470588235294

In [135]:
svm_clf_r.n_support_

array([186, 218])

# Grid search for radial kernel

In [145]:
params = {'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
           'gamma':(0.001, 0.01, 0.1, 0.5, 1)}

In [147]:
svm_clf_r = svm.SVC(kernel="rbf")

In [148]:
svm_grid_r= GridSearchCV(svm_clf_r, params, n_jobs=-1, cv=3, verbose=1, scoring="accuracy")

In [149]:
svm_grid_r.fit(X_train_std, y_train)

Fitting 3 folds for each of 40 candidates, totalling 120 fits


GridSearchCV(cv=3, estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
             scoring='accuracy', verbose=1)

In [150]:
svm_grid_r.best_params_

{'C': 50, 'gamma': 0.001}

In [151]:
radsvm_clf =svm_grid_r.best_estimator_

In [152]:
accuracy_score(y_test, radsvm_clf.predict(X_test_std))

0.6176470588235294